/* Autogenerated by hxtools bin2c */
#ifndef ICON_IMAGES_HPP
#define ICON_IMAGES_HPP 1

class wxBitmap;

extern "C" void bin2c_init_ICON_IMAGES_HPP(void);
extern wxBitmap *bin2c__360_png;
extern wxBitmap *bin2c__3d_cube_png;
extern wxBitmap *bin2c__3d_model_png;
extern wxBitmap *bin2c_anchor_png;
extern wxBitmap *bin2c_animated_mesh_png;
extern wxBitmap *bin2c_billboard_png;
extern wxBitmap *bin2c_camera_png;
extern wxBitmap *bin2c_canvas_png;
extern wxBitmap *bin2c_cursor_png;
extern wxBitmap *bin2c_cylinder_png;
extern wxBitmap *bin2c_delete_folder_png;
extern wxBitmap *bin2c_edit_folder_png;
extern wxBitmap *bin2c_edit_pencil_icon_png;
extern wxBitmap *bin2c_effect_png;
extern wxBitmap *bin2c_face_png;
extern wxBitmap *bin2c_files_png;
extern wxBitmap *bin2c_globe_png;
extern wxBitmap *bin2c_grass_png;
extern wxBitmap *bin2c_lamp_png;
extern wxBitmap *bin2c_light_bulb_png;
extern wxBitmap *bin2c_line_png;
extern wxBitmap *bin2c_mesh_png;
extern wxBitmap *bin2c_minus_png;
extern wxBitmap *bin2c_monitor_png;
extern wxBitmap *bin2c_move_png;
extern wxBitmap *bin2c_new_folder_png;
extern wxBitmap *bin2c_no_light_png;
extern wxBitmap *bin2c_plane_png;
extern wxBitmap *bin2c_play_png;
extern wxBitmap *bin2c_plus_png;
extern wxBitmap *bin2c_plus_stage_png;
extern wxBitmap *bin2c_point_light_png;
extern wxBitmap *bin2c_point_png;
extern wxBitmap *bin2c_redo_png;
extern wxBitmap *bin2c_remove_actor_png;
extern wxBitmap *bin2c_remove_stage_png;
extern wxBitmap *bin2c_rotate2D_png;
extern wxBitmap *bin2c_scale_png;
extern wxBitmap *bin2c_sea_png;
extern wxBitmap *bin2c_selection_box_png;
extern wxBitmap *bin2c_setting_png;
extern wxBitmap *bin2c_solid_png;
extern wxBitmap *bin2c_sphere_png;
extern wxBitmap *bin2c_spot_light_png;
extern wxBitmap *bin2c_stop_png;
extern wxBitmap *bin2c_terrain_png;
extern wxBitmap *bin2c_undo_png;
extern wxBitmap *bin2c_wireframe_png;
extern wxBitmap *bin2c_X_png;
extern wxBitmap *bin2c_x_transform_tool_png;
extern wxBitmap *bin2c_Y_png;
extern wxBitmap *bin2c_y_transform_tool_png;
extern wxBitmap *bin2c_Z_png;
extern wxBitmap *bin2c_z_transform_tool_png;


#endif /* ICON_IMAGES_HPP */
