#ifndef __SerenityEditor_NewStage_Dialog__
#define __SerenityEditor_NewStage_Dialog__

/**
@file
Subclass of NewStage_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing NewStage_Dialog */
class SerenityEditor_NewStage_Dialog : public NewStage_Dialog
{
	protected:
		// Handlers for NewStage_Dialog events.
		void OnCreate( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		bool create_flag;
		wxString stage_id;
		/** Constructor */
		SerenityEditor_NewStage_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_NewStage_Dialog__
