#ifndef __SerenityEditor_FXVariable_Dialog__
#define __SerenityEditor_FXVariable_Dialog__

/**
@file
Subclass of FXVariable_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing FXVariable_Dialog */
class SerenityEditor_FXVariable_Dialog : public FXVariable_Dialog
{
	protected:
		// Handlers for FXVariable_Dialog events.
		void OnVariableChange( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
		void OnSet( wxCommandEvent& event );
	public:
		/** Constructor */
		SerenityEditor_FXVariable_Dialog( wxWindow* parent );

		void initTitle(wxString title_str);
		void initVariable(wxString var_name, double n1, double n2, double n3, double n4);

		bool set_flag = false;
		wxString f_name = _("");
		double f_value[4];
		int var_type = 0;
	//// end generated class members

};

#endif // __SerenityEditor_FXVariable_Dialog__
