#ifndef __SerenityEditor_NewSphereActor_Dialog__
#define __SerenityEditor_NewSphereActor_Dialog__

/**
@file
Subclass of NewSphereActor_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing NewSphereActor_Dialog */
class SerenityEditor_NewSphereActor_Dialog : public NewSphereActor_Dialog
{
	protected:
		// Handlers for NewSphereActor_Dialog events.
		void OnCancelButtonClicked( wxCommandEvent& event );
		void OnCreateButtonClicked( wxCommandEvent& event );
	public:
		wxString id_name;
		bool create_flag;

		double radius;

		/** Constructor */
		SerenityEditor_NewSphereActor_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_NewSphereActor_Dialog__
