#ifndef __SerenityEditor_NewParticleActor_Dialog__
#define __SerenityEditor_NewParticleActor_Dialog__

/**
@file
Subclass of NewParticleActor_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing NewParticleActor_Dialog */
class SerenityEditor_NewParticleActor_Dialog : public NewParticleActor_Dialog
{
	protected:
		// Handlers for NewParticleActor_Dialog events.
		void OnCancelButtonClicked( wxCommandEvent& event );
		void OnCreateButtonClicked( wxCommandEvent& event );
	public:
		/** Constructor */
		SerenityEditor_NewParticleActor_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_NewParticleActor_Dialog__
