#ifndef __SerenityEditor_AddTexture_Dialog__
#define __SerenityEditor_AddTexture_Dialog__

/**
@file
Subclass of AddTexture_Dialog, which is generated by wxFormBuilder.
*/

#include <wx/wx.h>
#include "Serenity3D_Editor.h"
#include <vector>

//// end generated include

/** Implementing AddTexture_Dialog */
class SerenityEditor_AddTexture_Dialog : public AddTexture_Dialog
{
	protected:
		// Handlers for AddTexture_Dialog events.
		void OnSelectAll( wxCommandEvent& event );
		void OnDeselectAll( wxCommandEvent& event );
		void OnShowDuplicates( wxCommandEvent& event );
		void OnHideDuplicates( wxCommandEvent& event );
		void OnLoad( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		std::vector<wxString> project_files;
		std::vector<wxString> selected_files;

		wxFileName texture_path;
		bool show_duplicates = false;

		void refresh_list();
		bool isDuplicate(wxString filename);

		/** Constructor */
		SerenityEditor_AddTexture_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_AddTexture_Dialog__
