#ifndef __SerenityEditor_ExitEditorAlert_Dialog__
#define __SerenityEditor_ExitEditorAlert_Dialog__

/**
@file
Subclass of ExitEditorAlert_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing ExitEditorAlert_Dialog */
class SerenityEditor_ExitEditorAlert_Dialog : public ExitEditorAlert_Dialog
{
	protected:
		// Handlers for ExitEditorAlert_Dialog events.
		void OnSave( wxCommandEvent& event );
		void OnDiscard( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		bool save_flag;
		bool exit_flag;
		/** Constructor */
		SerenityEditor_ExitEditorAlert_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_ExitEditorAlert_Dialog__
