#ifndef __SerenityEditor_SetCamera_Dialog__
#define __SerenityEditor_SetCamera_Dialog__

/**
@file
Subclass of SetCamera_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing SetCamera_Dialog */
class SerenityEditor_SetCamera_Dialog : public SetCamera_Dialog
{
	protected:
		// Handlers for SetCamera_Dialog events.
		void OnCancel( wxCommandEvent& event );
		void OnSet( wxCommandEvent& event );
	public:
		double px, py, pz;
		double rx, ry, rz;

		bool set_flag;

		void refresh_values();

		/** Constructor */
		SerenityEditor_SetCamera_Dialog( wxWindow* parent );
	//// end generated class members


};

#endif // __SerenityEditor_SetCamera_Dialog__
