#ifndef __SerenityEditor_NewProject_Dialog__
#define __SerenityEditor_NewProject_Dialog__

/**
@file
Subclass of NewProject_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing NewProject_Dialog */
class SerenityEditor_NewProject_Dialog : public NewProject_Dialog
{
	protected:
		// Handlers for NewProject_Dialog events.
		void OnCancelButtonClicked( wxCommandEvent& event );
		void OnCreateButtonClicked( wxCommandEvent& event );
	public:
		wxString project_name;
		wxFileName project_file;
		bool createFlag = false;

		/** Constructor */
		SerenityEditor_NewProject_Dialog( wxWindow* parent );
	//// end generated class members


};

#endif // __SerenityEditor_NewProject_Dialog__
