#ifndef __SerenityEditorSerenity3D_Frame__
#define __SerenityEditorSerenity3D_Frame__

/**
@file
Subclass of Serenity3D_Frame, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"
#include "wxIrrlicht.h"
//// end generated include

/** Implementing Serenity3D_Frame */
class SerenityEditorSerenity3D_Frame : public Serenity3D_Frame
{
	public:
		/** Constructor */
		SerenityEditorSerenity3D_Frame( wxWindow* parent );

		int ClientH(float pct) { return (int) (GetClientSize().y * pct / 100); }
		int ClientW(float pct) { return (int) (GetClientSize().x * pct / 100); }

		wxIrrlicht* stage_window = NULL;
		wxIrrlicht* animation_window = NULL;

    protected:
		void OnPlayClicked( wxCommandEvent& event );
		void OnStopClicked( wxCommandEvent& event );
		void OnAnimationStopClicked( wxCommandEvent& event );

		void OnAnimationPreviewSize( wxSizeEvent& event );
	//// end generated class members

};

#endif // __SerenityEditorSerenity3D_Frame__
