#ifndef __SerenityEditor_NewCubeActor_Dialog__
#define __SerenityEditor_NewCubeActor_Dialog__

/**
@file
Subclass of NewCubeActor_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing NewCubeActor_Dialog */
class SerenityEditor_NewCubeActor_Dialog : public NewCubeActor_Dialog
{
	protected:
		// Handlers for NewCubeActor_Dialog events.
		void OnCancelButtonClicked( wxCommandEvent& event );
		void OnCreateButtonClicked( wxCommandEvent& event );
	public:
		wxString id_name;
		bool create_flag;

		double cube_size;

		/** Constructor */
		SerenityEditor_NewCubeActor_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_NewCubeActor_Dialog__
