#ifndef __SerenityEditor_NewLightActor_Dialog__
#define __SerenityEditor_NewLightActor_Dialog__

/**
@file
Subclass of NewLightActor_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing NewLightActor_Dialog */
class SerenityEditor_NewLightActor_Dialog : public NewLightActor_Dialog
{
	protected:
		// Handlers for NewLightActor_Dialog events.
		void OnCancelButtonClicked( wxCommandEvent& event );
		void OnCreateButtonClicked( wxCommandEvent& event );
	public:
		wxString id_name;
		wxString light_type;
		wxArrayString light_type_list;
		bool create_flag;

		void refresh_list();

		/** Constructor */
		SerenityEditor_NewLightActor_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_NewLightActor_Dialog__
