#ifndef __SerenityEditorSerenity3D_Frame__
#define __SerenityEditorSerenity3D_Frame__

/**
@file
Subclass of Serenity3D_Frame, which is generated by wxFormBuilder.
*/

#include <vector>
#include "Serenity3D_Editor.h"
#include "wxIrrlicht.h"
#include "engine_base.h"
#include "rc_stage.h"
#include "MeshTab_SetMaterialSelection.h"
//// end generated include

/** Implementing Serenity3D_Frame */
class SerenityEditorSerenity3D_Frame : public Serenity3D_Frame
{
	public:
		/** Constructor */
		SerenityEditorSerenity3D_Frame( wxWindow* parent );

		wxFileName asset_dir;

		serenity_project project;

		int viewport_mode = 0;
		int mouse_button = 0;
		int mouse_x = -1;
		int mouse_y = -1;

		int viewport_camera_mouse_x = 0;
		int viewport_camera_mouse_y = 0;
		bool viewport_camera_active = false;

		int ClientH(float pct) { return (int) (GetClientSize().y * pct / 100); }
		int ClientW(float pct) { return (int) (GetClientSize().x * pct / 100); }

		wxIrrlicht* stage_window = NULL;
		wxIrrlicht* animation_window = NULL;

		std::vector<wxAuiToolBarItem*> stage_tools;
		int stage_tools_selection = 0;

		void updateToolSelection();
		int getStageToolIndex(wxAuiToolBarItem* toolbar_item);

		//--------MESH TAB--------------
		int meshTab_selected_mesh_project_index = -1;

		wxBoxSizer* b_setMaterial_Sizer;
		std::vector<MT_SetMaterialPanel*> mesh_material_items;

		void clearMeshMaterialList();
		void appendMeshMaterialList(int material_index); //index in project.materials[], pass -1 if no material is set


		int meshTab_selected_animation_index = -1;

    protected:
    	void OnNewProjectMenuSelection( wxCommandEvent& event );
    	void OnS3DSelectClicked( wxCommandEvent& event );
		void OnS3DBoxClicked( wxCommandEvent& event );
		void OnS3DMoveClicked( wxCommandEvent& event );
		void OnS3DRotateClicked( wxCommandEvent& event );
		void OnS3DScaleClicked( wxCommandEvent& event );
		void OnS3DPlaneClicked( wxCommandEvent& event );
		void OnS3DCubeClicked( wxCommandEvent& event );
		void OnS3DSphereClicked( wxCommandEvent& event );
		void OnS3DCylinderClicked( wxCommandEvent& event );
		void OnS3DDumpClicked( wxCommandEvent& event );
		void OnS3DWizClicked( wxCommandEvent& event );
		void OnS3DBillboardClicked( wxCommandEvent& event );
		void OnS3DLightClicked( wxCommandEvent& event );
		void OnS3DTerrainClicked( wxCommandEvent& event );
		void OnS3DWaterClicked( wxCommandEvent& event );
		void OnS3DGrassClicked( wxCommandEvent& event );
		void OnS3DPathClicked( wxCommandEvent& event );
		void OnS3DEffectClicked( wxCommandEvent& event );
		void OnS3DModeEditClicked( wxCommandEvent& event );
		void OnS3DModeCameraClicked( wxCommandEvent& event );

		void OnPlayClicked( wxCommandEvent& event );
		void OnStopClicked( wxCommandEvent& event );
		void OnAnimationStopClicked( wxCommandEvent& event );

		void OnAnimationPreviewSize( wxSizeEvent& event );
		void OnStageViewportMouse( wxMouseEvent& event );

		void OnStageViewportSetFocus( wxFocusEvent& event );
		void OnStageViewportKillFocus( wxFocusEvent& event );
		void OnStageContainerMouse( wxMouseEvent& event );

		void OnViewComboSelect( wxCommandEvent& event );

		void OnMeshImportButtonClick( wxCommandEvent& event );
	//// end generated class members

};

#endif // __SerenityEditorSerenity3D_Frame__
