#ifndef __SerenityEditor_NewOctree_Dialog__
#define __SerenityEditor_NewOctree_Dialog__

/**
@file
Subclass of NewOctree_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"
#include "engine_base.h"

//// end generated include

/** Implementing NewOctree_Dialog */
class SerenityEditor_NewOctree_Dialog : public NewOctree_Dialog
{
	protected:
		// Handlers for NewOctree_Dialog events.
		void OnCancelButtonClicked( wxCommandEvent& event );
		void OnCreateButtonClicked( wxCommandEvent& event );
	public:
		serenity_project* project;

		/** Constructor */
		SerenityEditor_NewOctree_Dialog( wxWindow* parent, serenity_project* prj );
	//// end generated class members

};

#endif // __SerenityEditor_NewOctree_Dialog__
