#ifndef __SerenityEditor_NewAnimatedActor_Dialog__
#define __SerenityEditor_NewAnimatedActor_Dialog__

/**
@file
Subclass of NewAnimatedActor_Dialog, which is generated by wxFormBuilder.
*/

#include <wx/wx.h>
#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing NewAnimatedActor_Dialog */
class SerenityEditor_NewAnimatedActor_Dialog : public NewAnimatedActor_Dialog
{
	protected:
		// Handlers for NewAnimatedActor_Dialog events.
		void OnSearchText( wxCommandEvent& event );
		void OnCancelButtonClicked( wxCommandEvent& event );
		void OnCreateButtonClicked( wxCommandEvent& event );
	public:
		wxString id_name;
		wxString mesh_id_name;
		wxArrayString meshes;
		bool create_flag;

		void refresh_list();

		/** Constructor */
		SerenityEditor_NewAnimatedActor_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_NewAnimatedActor_Dialog__
