#ifndef __SerenityEditor_EditStageGroup_Dialog__
#define __SerenityEditor_EditStageGroup_Dialog__

/**
@file
Subclass of EditStageGroup_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing EditStageGroup_Dialog */
class SerenityEditor_EditStageGroup_Dialog : public EditStageGroup_Dialog
{
	protected:
		// Handlers for EditStageGroup_Dialog events.
		void OnStageSelectAll( wxCommandEvent& event );
		void OnStageDeselectAll( wxCommandEvent& event );
		void OnAdd( wxCommandEvent& event );
		void OnRemove( wxCommandEvent& event );
		void OnGroupSelectAll( wxCommandEvent& event );
		void OnGroupDeselectAll( wxCommandEvent& event );
		void OnApply( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		wxArrayString src_actors;
		wxArrayString dst_actors;
		wxString group_name;
		wxString stage_id;

		bool applyFlag;

		void refresh_list();
		void refresh_groupName();

		/** Constructor */
		SerenityEditor_EditStageGroup_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_EditStageGroup_Dialog__
