#ifndef __SerenityEditor_SetMeshMaterialLevel_Dialog__
#define __SerenityEditor_SetMeshMaterialLevel_Dialog__

/**
@file
Subclass of SetMeshMaterialLevel_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing SetMeshMaterialLevel_Dialog */
class SerenityEditor_SetMeshMaterialLevel_Dialog : public SetMeshMaterialLevel_Dialog
{
	protected:
		// Handlers for SetMeshMaterialLevel_Dialog events.
		void OnSearch( wxCommandEvent& event );
		void OnSetMaterial( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		wxArrayString id_list;
		wxString selected_material_id;

		void refresh_list();

		/** Constructor */
		SerenityEditor_SetMeshMaterialLevel_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_SetMeshMaterialLevel_Dialog__
