#ifndef __SerenityEditor_SetMaterialTextureLevel_Dialog__
#define __SerenityEditor_SetMaterialTextureLevel_Dialog__

/**
@file
Subclass of SetMaterialTextureLevel_Dialog, which is generated by wxFormBuilder.
*/
#include <wx/wx.h>
#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing SetMaterialTextureLevel_Dialog */
class SerenityEditor_SetMaterialTextureLevel_Dialog : public SetMaterialTextureLevel_Dialog
{
	protected:
		// Handlers for SetMaterialTextureLevel_Dialog events.
		void OnSetTexture( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
		void OnSearch( wxCommandEvent& event );
	public:
		wxArrayString id_list;
		wxString selected_texture_id;

		void refresh_list();

		/** Constructor */
		SerenityEditor_SetMaterialTextureLevel_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_SetMaterialTextureLevel_Dialog__
