#ifndef __SerenityEditor_DeleteActorAlert_Dialog__
#define __SerenityEditor_DeleteActorAlert_Dialog__

/**
@file
Subclass of DeleteActorAlert_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing DeleteActorAlert_Dialog */
class SerenityEditor_DeleteActorAlert_Dialog : public DeleteActorAlert_Dialog
{
	protected:
		// Handlers for DeleteActorAlert_Dialog events.
		void OnDelete( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		bool delete_flag;

		void setActorID(wxString actor_id);
		/** Constructor */
		SerenityEditor_DeleteActorAlert_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_DeleteActorAlert_Dialog__
