#ifndef __SerenityEditor_CreateStageGroup_Dialog__
#define __SerenityEditor_CreateStageGroup_Dialog__

/**
@file
Subclass of CreateStageGroup_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing CreateStageGroup_Dialog */
class SerenityEditor_CreateStageGroup_Dialog : public CreateStageGroup_Dialog
{
	protected:
		// Handlers for CreateStageGroup_Dialog events.
		void OnCreate( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		/** Constructor */
		SerenityEditor_CreateStageGroup_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_CreateStageGroup_Dialog__
