#ifndef __SerenityEditor_MaterialPreviewSettings_Dialog__
#define __SerenityEditor_MaterialPreviewSettings_Dialog__

/**
@file
Subclass of MaterialPreviewSettings_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing MaterialPreviewSettings_Dialog */
class SerenityEditor_MaterialPreviewSettings_Dialog : public MaterialPreviewSettings_Dialog
{
	protected:
		// Handlers for MaterialPreviewSettings_Dialog events.
		void OnApply( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		double camera_speed;
		double camera_distance;
		double light_radius;

		int control_type;

		void setFields(double speed, double distance, double radius, int control);

		bool apply_changes;
		/** Constructor */
		SerenityEditor_MaterialPreviewSettings_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_MaterialPreviewSettings_Dialog__
