#ifndef __SerenityEditor_DeleteGroupAlert_Dialog__
#define __SerenityEditor_DeleteGroupAlert_Dialog__

/**
@file
Subclass of DeleteGroupAlert_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing DeleteGroupAlert_Dialog */
class SerenityEditor_DeleteGroupAlert_Dialog : public DeleteGroupAlert_Dialog
{
	protected:
		// Handlers for DeleteGroupAlert_Dialog events.
		void OnDelete( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		void setGroupName(wxString group_name);

		bool deleteFlag;

		/** Constructor */
		SerenityEditor_DeleteGroupAlert_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_DeleteGroupAlert_Dialog__
