#ifndef __SerenityEditor_NewBillboardActor_Dialog__
#define __SerenityEditor_NewBillboardActor_Dialog__

/**
@file
Subclass of NewBillboardActor_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing NewBillboardActor_Dialog */
class SerenityEditor_NewBillboardActor_Dialog : public NewBillboardActor_Dialog
{
	protected:
		// Handlers for NewBillboardActor_Dialog events.
		void OnSearchText( wxCommandEvent& event );
		void OnCancelButtonClicked( wxCommandEvent& event );
		void OnCreateButtonClicked( wxCommandEvent& event );
	public:
		/** Constructor */
		SerenityEditor_NewBillboardActor_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_NewBillboardActor_Dialog__
