#ifndef __SerenityEditor_AddMesh_Dialog__
#define __SerenityEditor_AddMesh_Dialog__

/**
@file
Subclass of AddMesh_Dialog, which is generated by wxFormBuilder.
*/

#include <wx/wx.h>
#include <vector>
#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing AddMesh_Dialog */
class SerenityEditor_AddMesh_Dialog : public AddMesh_Dialog
{
	protected:
		// Handlers for AddMesh_Dialog events.
		void OnSelectAll( wxCommandEvent& event );
		void OnDeselectAll( wxCommandEvent& event );
		void OnShowDuplicates( wxCommandEvent& event );
		void OnHideDuplicates( wxCommandEvent& event );
		void OnLoad( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		std::vector<wxString> project_files;
		std::vector<wxString> selected_files;

		wxFileName model_path;
		bool show_duplicates = false;

		void refresh_list();
		bool isDuplicate(wxString filename);

		/** Constructor */
		SerenityEditor_AddMesh_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_AddMesh_Dialog__
