#ifndef __SerenityEditor_NewTerrainActor_Dialog__
#define __SerenityEditor_NewTerrainActor_Dialog__

/**
@file
Subclass of NewTerrainActor_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing NewTerrainActor_Dialog */
class SerenityEditor_NewTerrainActor_Dialog : public NewTerrainActor_Dialog
{
	protected:
		// Handlers for NewTerrainActor_Dialog events.
		void OnSearchText( wxCommandEvent& event );
		void OnCancelButtonClicked( wxCommandEvent& event );
		void OnCreateButtonClicked( wxCommandEvent& event );
	public:
		/** Constructor */
		SerenityEditor_NewTerrainActor_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_NewTerrainActor_Dialog__
