#ifndef __SerenityEditor_DeleteStageAlert_Dialog__
#define __SerenityEditor_DeleteStageAlert_Dialog__

/**
@file
Subclass of DeleteStageAlert_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing DeleteStageAlert_Dialog */
class SerenityEditor_DeleteStageAlert_Dialog : public DeleteStageAlert_Dialog
{
	protected:
		// Handlers for DeleteStageAlert_Dialog events.
		void OnDelete( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		bool delete_flag;

		void setStageID(wxString stage_id);
		/** Constructor */
		SerenityEditor_DeleteStageAlert_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_DeleteStageAlert_Dialog__
