#ifndef __SerenityEditor_SetMaterialPreviewMesh_Dialog__
#define __SerenityEditor_SetMaterialPreviewMesh_Dialog__

/**
@file
Subclass of SetMaterialPreviewMesh_Dialog, which is generated by wxFormBuilder.
*/

#include <wx/wx.h>
#include <vector>

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing SetMaterialPreviewMesh_Dialog */
class SerenityEditor_SetMaterialPreviewMesh_Dialog : public SetMaterialPreviewMesh_Dialog
{
	protected:
		// Handlers for SetMaterialPreviewMesh_Dialog events.
		void OnSearch( wxCommandEvent& event );
		void OnSetMesh( wxCommandEvent& event );
		void OnDefaultCube( wxCommandEvent& event );
		void OnDefaultSphere( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		wxArrayString mesh_list;
		wxString selected_mesh_id;
		void refresh_list();
		/** Constructor */
		SerenityEditor_SetMaterialPreviewMesh_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_SetMaterialPreviewMesh_Dialog__
