#ifndef __SerenityEditor_AddMaterial_Dialog__
#define __SerenityEditor_AddMaterial_Dialog__

/**
@file
Subclass of AddMaterial_Dialog, which is generated by wxFormBuilder.
*/

#include "Serenity3D_Editor.h"

//// end generated include

/** Implementing AddMaterial_Dialog */
class SerenityEditor_AddMaterial_Dialog : public AddMaterial_Dialog
{
	protected:
		// Handlers for AddMaterial_Dialog events.
		void OnSelectAll( wxCommandEvent& event );
		void OnDeselectAll( wxCommandEvent& event );
		void OnShowDuplicates( wxCommandEvent& event );
		void OnHideDuplicates( wxCommandEvent& event );
		void OnLoad( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		std::vector<wxString> project_files;
		std::vector<wxString> selected_files;

		wxFileName material_path;
		bool show_duplicates = false;

		void refresh_list();
		bool isDuplicate(wxString filename);

		/** Constructor */
		SerenityEditor_AddMaterial_Dialog( wxWindow* parent );
	//// end generated class members

};

#endif // __SerenityEditor_AddMaterial_Dialog__
